- name: Installing Veeam ONE Install (Typical Deployment)
  gather_facts: no
  hosts: veeam

  vars:
    version: "12"
    iso_download: false #this way ISO is only downloaded once
    sql_express_setup: true
    sql_service_username: "svc_sql"
    sql_service_password: "ChangeM3!"
    one_create_service_account: true #true==local false==domain
    one_username: "svc_one"
    one_password: "ChangeM3!"
    # https://docs.ansible.com/ansible/latest/user_guide/playbooks_vault.html#single-encrypted-variable
  tasks:
    - name: Veeam ONE Server installation tasks
      include_role:
        name: veeamhub.veeam.veeam_vas
        tasks_from: one_server_install
      vars:
        iso_download: true #this way ISO is only downloaded once
    - name: Veeam ONE Web UI installation tasks
      include_role:
        name: veeamhub.veeam.veeam_vas
        tasks_from: one_web_ui_install
    - name: Veeam ONE Monitoring Client installation tasks
      include_role:
        name: veeamhub.veeam.veeam_vas
        tasks_from: one_client_install