- name: Veeam Backup & Replication Install with Remote PostgreSQL Server
  hosts: veeam
  tasks:
    - include_role:
        name: veeamhub.veeam.veeam_vas
        tasks_from: vbr_install
      vars:
        version: "12"
        license: true
        source_license: "/root/ansible/license.lic"
        sql_express_setup: false        
        sql_instance: "sql.contoso.local"
        sql_username: "svc_veeam"
        sql_password: "ChangeM3!"
        # https://docs.ansible.com/ansible/latest/user_guide/playbooks_vault.html#single-encrypted-variable
    - name: Applying tuning on a remote PostgreSQL server running as the VBR DB
       veeamhub.veeam.veeam_vbr_set_postgres_database_server_limits:
         os_type: Windows
         cpu_count: 16
         ram_gb: 30