- name: Veeam Backup Enterprise Manager Patch
  hosts: veeam
  tasks:
    - include_role:
        name: veeamhub.veeam.veeam_vas
        tasks_from: em_patch
      vars:
        source: "C:\\install\\"
        patch_file: "VeeamBackup&Replication_10.0.0.4461.update0.exe"
        sql_instance: "sql.contoso.local"
        sql_database: "VeeamBackupReporting"
        sql_username: "sa"
        sql_password: "ChangeM3!"
        # https://docs.ansible.com/ansible/latest/user_guide/playbooks_vault.html#single-encrypted-variable